// unassigned survey
export const SURVEY_LIST_REQUEST = "SURVEY_LIST_REQUEST";
export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SURVEY_LIST_FAIL = "SURVEY_LIST_FAIL";

// assign survey
export const ASSIGNED_REQUEST = "ASSIGNED_REQUEST";
export const ASSIGNED_SUCCESS = "ASSIGNED_SUCCESS";
export const ASSIGNED_FAIL = "ASSIGNED_FAIL";
